"""

Revision ID: ff4e0793734d
Revises: 230a9f7ae0f3
Create Date: 2026-03-31 13:31:35.767619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4e0793734d'
down_revision = '230a9f7ae0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_spec_points', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    with op.batch_alter_table('measurement_draft_specs', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
